/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotepageRouteImport } from './routes/$notepage'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as NotellaRouteImport } from './routes/notella'
import { Route as NotepagesRouteImport } from './routes/notepages'
import { Route as NotetagsRouteImport } from './routes/notetags'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WriteRouteImport } from './routes/write'
import { Route as NotepageIndexRouteImport } from './routes/$notepage.index'
import { Route as NotepagesIndexRouteImport } from './routes/notepages.index'
import { Route as NotepagesNewRouteImport } from './routes/notepages.new'
import { Route as NotetagsIndexRouteImport } from './routes/notetags.index'
import { Route as NotetagsTagRouteImport } from './routes/notetags.$tag'
import { Route as NotepageNotepageNoteIdRouteImport } from './routes/$notepage.notepage.$noteId'
import { Route as NotepageNotetagsTagRouteImport } from './routes/$notepage.notetags.$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotepageRoute = NotepageRouteImport.update({
  id: '/$notepage',
  path: '/$notepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const NotellaRoute = NotellaRouteImport.update({
  id: '/notella',
  path: '/notella',
  getParentRoute: () => rootRouteImport,
} as any)
const NotepagesRoute = NotepagesRouteImport.update({
  id: '/notepages',
  path: '/notepages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotetagsRoute = NotetagsRouteImport.update({
  id: '/notetags',
  path: '/notetags',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const NotepageIndexRoute = NotepageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotepageRoute,
} as any)
const NotepagesIndexRoute = NotepagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotepagesRoute,
} as any)
const NotepagesNewRoute = NotepagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NotepagesRoute,
} as any)
const NotetagsIndexRoute = NotetagsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotetagsRoute,
} as any)
const NotetagsTagRoute = NotetagsTagRouteImport.update({
  id: '/$tag',
  path: '/$tag',
  getParentRoute: () => NotetagsRoute,
} as any)
const NotepageNotepageNoteIdRoute = NotepageNotepageNoteIdRouteImport.update({
  id: '/notepage/$noteId',
  path: '/notepage/$noteId',
  getParentRoute: () => NotepageRoute,
} as any)
const NotepageNotetagsTagRoute = NotepageNotetagsTagRouteImport.update({
  id: '/notetags/$tag',
  path: '/notetags/$tag',
  getParentRoute: () => NotepageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$notepage': typeof NotepageRouteWithChildren
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/guidelines': typeof GuidelinesRoute
  '/notella': typeof NotellaRoute
  '/notepages': typeof NotepagesRouteWithChildren
  '/notetags': typeof NotetagsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRoute
  '/notepages/new': typeof NotepagesNewRoute
  '/notetags/$tag': typeof NotetagsTagRoute
  '/$notepage/': typeof NotepageIndexRoute
  '/notepages/': typeof NotepagesIndexRoute
  '/notetags/': typeof NotetagsIndexRoute
  '/$notepage/notepage/$noteId': typeof NotepageNotepageNoteIdRoute
  '/$notepage/notetags/$tag': typeof NotepageNotetagsTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/guidelines': typeof GuidelinesRoute
  '/notella': typeof NotellaRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRoute
  '/notepages/new': typeof NotepagesNewRoute
  '/notetags/$tag': typeof NotetagsTagRoute
  '/$notepage': typeof NotepageIndexRoute
  '/notepages': typeof NotepagesIndexRoute
  '/notetags': typeof NotetagsIndexRoute
  '/$notepage/notepage/$noteId': typeof NotepageNotepageNoteIdRoute
  '/$notepage/notetags/$tag': typeof NotepageNotetagsTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$notepage': typeof NotepageRouteWithChildren
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/guidelines': typeof GuidelinesRoute
  '/notella': typeof NotellaRoute
  '/notepages': typeof NotepagesRouteWithChildren
  '/notetags': typeof NotetagsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRoute
  '/notepages/new': typeof NotepagesNewRoute
  '/notetags/$tag': typeof NotetagsTagRoute
  '/$notepage/': typeof NotepageIndexRoute
  '/notepages/': typeof NotepagesIndexRoute
  '/notetags/': typeof NotetagsIndexRoute
  '/$notepage/notepage/$noteId': typeof NotepageNotepageNoteIdRoute
  '/$notepage/notetags/$tag': typeof NotepageNotetagsTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$notepage'
    | '/about'
    | '/explore'
    | '/guidelines'
    | '/notella'
    | '/notepages'
    | '/notetags'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/write'
    | '/notepages/new'
    | '/notetags/$tag'
    | '/$notepage/'
    | '/notepages/'
    | '/notetags/'
    | '/$notepage/notepage/$noteId'
    | '/$notepage/notetags/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/guidelines'
    | '/notella'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/write'
    | '/notepages/new'
    | '/notetags/$tag'
    | '/$notepage'
    | '/notepages'
    | '/notetags'
    | '/$notepage/notepage/$noteId'
    | '/$notepage/notetags/$tag'
  id:
    | '__root__'
    | '/'
    | '/$notepage'
    | '/about'
    | '/explore'
    | '/guidelines'
    | '/notella'
    | '/notepages'
    | '/notetags'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/write'
    | '/notepages/new'
    | '/notetags/$tag'
    | '/$notepage/'
    | '/notepages/'
    | '/notetags/'
    | '/$notepage/notepage/$noteId'
    | '/$notepage/notetags/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotepageRoute: typeof NotepageRouteWithChildren
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  GuidelinesRoute: typeof GuidelinesRoute
  NotellaRoute: typeof NotellaRoute
  NotepagesRoute: typeof NotepagesRouteWithChildren
  NotetagsRoute: typeof NotetagsRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
  WriteRoute: typeof WriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$notepage': {
      id: '/$notepage'
      path: '/$notepage'
      fullPath: '/$notepage'
      preLoaderRoute: typeof NotepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notella': {
      id: '/notella'
      path: '/notella'
      fullPath: '/notella'
      preLoaderRoute: typeof NotellaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notepages': {
      id: '/notepages'
      path: '/notepages'
      fullPath: '/notepages'
      preLoaderRoute: typeof NotepagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notetags': {
      id: '/notetags'
      path: '/notetags'
      fullPath: '/notetags'
      preLoaderRoute: typeof NotetagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$notepage/': {
      id: '/$notepage/'
      path: '/'
      fullPath: '/$notepage/'
      preLoaderRoute: typeof NotepageIndexRouteImport
      parentRoute: typeof NotepageRoute
    }
    '/notepages/': {
      id: '/notepages/'
      path: '/'
      fullPath: '/notepages/'
      preLoaderRoute: typeof NotepagesIndexRouteImport
      parentRoute: typeof NotepagesRoute
    }
    '/notepages/new': {
      id: '/notepages/new'
      path: '/new'
      fullPath: '/notepages/new'
      preLoaderRoute: typeof NotepagesNewRouteImport
      parentRoute: typeof NotepagesRoute
    }
    '/notetags/': {
      id: '/notetags/'
      path: '/'
      fullPath: '/notetags/'
      preLoaderRoute: typeof NotetagsIndexRouteImport
      parentRoute: typeof NotetagsRoute
    }
    '/notetags/$tag': {
      id: '/notetags/$tag'
      path: '/$tag'
      fullPath: '/notetags/$tag'
      preLoaderRoute: typeof NotetagsTagRouteImport
      parentRoute: typeof NotetagsRoute
    }
    '/$notepage/notepage/$noteId': {
      id: '/$notepage/notepage/$noteId'
      path: '/notepage/$noteId'
      fullPath: '/$notepage/notepage/$noteId'
      preLoaderRoute: typeof NotepageNotepageNoteIdRouteImport
      parentRoute: typeof NotepageRoute
    }
    '/$notepage/notetags/$tag': {
      id: '/$notepage/notetags/$tag'
      path: '/notetags/$tag'
      fullPath: '/$notepage/notetags/$tag'
      preLoaderRoute: typeof NotepageNotetagsTagRouteImport
      parentRoute: typeof NotepageRoute
    }
  }
}

interface NotepageRouteChildren {
  NotepageIndexRoute: typeof NotepageIndexRoute
  NotepageNotepageNoteIdRoute: typeof NotepageNotepageNoteIdRoute
  NotepageNotetagsTagRoute: typeof NotepageNotetagsTagRoute
}

const NotepageRouteChildren: NotepageRouteChildren = {
  NotepageIndexRoute: NotepageIndexRoute,
  NotepageNotepageNoteIdRoute: NotepageNotepageNoteIdRoute,
  NotepageNotetagsTagRoute: NotepageNotetagsTagRoute,
}

const NotepageRouteWithChildren = NotepageRoute._addFileChildren(
  NotepageRouteChildren,
)

interface NotepagesRouteChildren {
  NotepagesNewRoute: typeof NotepagesNewRoute
  NotepagesIndexRoute: typeof NotepagesIndexRoute
}

const NotepagesRouteChildren: NotepagesRouteChildren = {
  NotepagesNewRoute: NotepagesNewRoute,
  NotepagesIndexRoute: NotepagesIndexRoute,
}

const NotepagesRouteWithChildren = NotepagesRoute._addFileChildren(
  NotepagesRouteChildren,
)

interface NotetagsRouteChildren {
  NotetagsTagRoute: typeof NotetagsTagRoute
  NotetagsIndexRoute: typeof NotetagsIndexRoute
}

const NotetagsRouteChildren: NotetagsRouteChildren = {
  NotetagsTagRoute: NotetagsTagRoute,
  NotetagsIndexRoute: NotetagsIndexRoute,
}

const NotetagsRouteWithChildren = NotetagsRoute._addFileChildren(
  NotetagsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotepageRoute: NotepageRouteWithChildren,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  GuidelinesRoute: GuidelinesRoute,
  NotellaRoute: NotellaRoute,
  NotepagesRoute: NotepagesRouteWithChildren,
  NotetagsRoute: NotetagsRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
  WriteRoute: WriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
