/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotepageRouteImport } from './routes/$notepage'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as InkProgramRouteImport } from './routes/ink-program'
import { Route as NotellaRouteImport } from './routes/notella'
import { Route as NotepagesRouteImport } from './routes/notepages'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WriteRouteImport } from './routes/write'
import { Route as NotepageIndexRouteImport } from './routes/$notepage.index'
import { Route as NotepageAboutRouteImport } from './routes/$notepage.about'
import { Route as NotepageGuestnoteRouteImport } from './routes/$notepage.guestnote'
import { Route as NotepageNotesRouteImport } from './routes/$notepage.notes'
import { Route as CustomizeNotepageRouteImport } from './routes/customize.$notepage'
import { Route as NotepagesIndexRouteImport } from './routes/notepages.index'
import { Route as NotepagesNotepageRouteImport } from './routes/notepages.$notepage'
import { Route as NotepagesNewRouteImport } from './routes/notepages.new'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsTagRouteImport } from './routes/topics.$tag'
import { Route as NotepageNotepageNoteIdRouteImport } from './routes/$notepage.notepage.$noteId'
import { Route as NotepageNotetagsTagRouteImport } from './routes/$notepage.notetags.$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotepageRoute = NotepageRouteImport.update({
  id: '/$notepage',
  path: '/$notepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const InkProgramRoute = InkProgramRouteImport.update({
  id: '/ink-program',
  path: '/ink-program',
  getParentRoute: () => rootRouteImport,
} as any)
const NotellaRoute = NotellaRouteImport.update({
  id: '/notella',
  path: '/notella',
  getParentRoute: () => rootRouteImport,
} as any)
const NotepagesRoute = NotepagesRouteImport.update({
  id: '/notepages',
  path: '/notepages',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const NotepageIndexRoute = NotepageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotepageRoute,
} as any)
const NotepageAboutRoute = NotepageAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => NotepageRoute,
} as any)
const NotepageGuestnoteRoute = NotepageGuestnoteRouteImport.update({
  id: '/guestnote',
  path: '/guestnote',
  getParentRoute: () => NotepageRoute,
} as any)
const NotepageNotesRoute = NotepageNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => NotepageRoute,
} as any)
const CustomizeNotepageRoute = CustomizeNotepageRouteImport.update({
  id: '/customize/$notepage',
  path: '/customize/$notepage',
  getParentRoute: () => rootRouteImport,
} as any)
const NotepagesIndexRoute = NotepagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotepagesRoute,
} as any)
const NotepagesNotepageRoute = NotepagesNotepageRouteImport.update({
  id: '/$notepage',
  path: '/$notepage',
  getParentRoute: () => NotepagesRoute,
} as any)
const NotepagesNewRoute = NotepagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NotepagesRoute,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTagRoute = TopicsTagRouteImport.update({
  id: '/topics/$tag',
  path: '/topics/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const NotepageNotepageNoteIdRoute = NotepageNotepageNoteIdRouteImport.update({
  id: '/notepage/$noteId',
  path: '/notepage/$noteId',
  getParentRoute: () => NotepageRoute,
} as any)
const NotepageNotetagsTagRoute = NotepageNotetagsTagRouteImport.update({
  id: '/notetags/$tag',
  path: '/notetags/$tag',
  getParentRoute: () => NotepageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$notepage': typeof NotepageRouteWithChildren
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/guidelines': typeof GuidelinesRoute
  '/ink-program': typeof InkProgramRoute
  '/notella': typeof NotellaRoute
  '/notepages': typeof NotepagesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRoute
  '/$notepage/about': typeof NotepageAboutRoute
  '/$notepage/guestnote': typeof NotepageGuestnoteRoute
  '/$notepage/notes': typeof NotepageNotesRoute
  '/customize/$notepage': typeof CustomizeNotepageRoute
  '/notepages/$notepage': typeof NotepagesNotepageRoute
  '/notepages/new': typeof NotepagesNewRoute
  '/topics/$tag': typeof TopicsTagRoute
  '/$notepage/': typeof NotepageIndexRoute
  '/notepages/': typeof NotepagesIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/$notepage/notepage/$noteId': typeof NotepageNotepageNoteIdRoute
  '/$notepage/notetags/$tag': typeof NotepageNotetagsTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/guidelines': typeof GuidelinesRoute
  '/ink-program': typeof InkProgramRoute
  '/notella': typeof NotellaRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRoute
  '/$notepage/about': typeof NotepageAboutRoute
  '/$notepage/guestnote': typeof NotepageGuestnoteRoute
  '/$notepage/notes': typeof NotepageNotesRoute
  '/customize/$notepage': typeof CustomizeNotepageRoute
  '/notepages/$notepage': typeof NotepagesNotepageRoute
  '/notepages/new': typeof NotepagesNewRoute
  '/topics/$tag': typeof TopicsTagRoute
  '/$notepage': typeof NotepageIndexRoute
  '/notepages': typeof NotepagesIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/$notepage/notepage/$noteId': typeof NotepageNotepageNoteIdRoute
  '/$notepage/notetags/$tag': typeof NotepageNotetagsTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$notepage': typeof NotepageRouteWithChildren
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/guidelines': typeof GuidelinesRoute
  '/ink-program': typeof InkProgramRoute
  '/notella': typeof NotellaRoute
  '/notepages': typeof NotepagesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/write': typeof WriteRoute
  '/$notepage/about': typeof NotepageAboutRoute
  '/$notepage/guestnote': typeof NotepageGuestnoteRoute
  '/$notepage/notes': typeof NotepageNotesRoute
  '/customize/$notepage': typeof CustomizeNotepageRoute
  '/notepages/$notepage': typeof NotepagesNotepageRoute
  '/notepages/new': typeof NotepagesNewRoute
  '/topics/$tag': typeof TopicsTagRoute
  '/$notepage/': typeof NotepageIndexRoute
  '/notepages/': typeof NotepagesIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/$notepage/notepage/$noteId': typeof NotepageNotepageNoteIdRoute
  '/$notepage/notetags/$tag': typeof NotepageNotetagsTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$notepage'
    | '/about'
    | '/explore'
    | '/guidelines'
    | '/ink-program'
    | '/notella'
    | '/notepages'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/sign-in'
    | '/terms'
    | '/write'
    | '/$notepage/about'
    | '/$notepage/guestnote'
    | '/$notepage/notes'
    | '/customize/$notepage'
    | '/notepages/$notepage'
    | '/notepages/new'
    | '/topics/$tag'
    | '/$notepage/'
    | '/notepages/'
    | '/topics/'
    | '/$notepage/notepage/$noteId'
    | '/$notepage/notetags/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/guidelines'
    | '/ink-program'
    | '/notella'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/sign-in'
    | '/terms'
    | '/write'
    | '/$notepage/about'
    | '/$notepage/guestnote'
    | '/$notepage/notes'
    | '/customize/$notepage'
    | '/notepages/$notepage'
    | '/notepages/new'
    | '/topics/$tag'
    | '/$notepage'
    | '/notepages'
    | '/topics'
    | '/$notepage/notepage/$noteId'
    | '/$notepage/notetags/$tag'
  id:
    | '__root__'
    | '/'
    | '/$notepage'
    | '/about'
    | '/explore'
    | '/guidelines'
    | '/ink-program'
    | '/notella'
    | '/notepages'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/sign-in'
    | '/terms'
    | '/write'
    | '/$notepage/about'
    | '/$notepage/guestnote'
    | '/$notepage/notes'
    | '/customize/$notepage'
    | '/notepages/$notepage'
    | '/notepages/new'
    | '/topics/$tag'
    | '/$notepage/'
    | '/notepages/'
    | '/topics/'
    | '/$notepage/notepage/$noteId'
    | '/$notepage/notetags/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotepageRoute: typeof NotepageRouteWithChildren
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  GuidelinesRoute: typeof GuidelinesRoute
  InkProgramRoute: typeof InkProgramRoute
  NotellaRoute: typeof NotellaRoute
  NotepagesRoute: typeof NotepagesRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  WriteRoute: typeof WriteRoute
  CustomizeNotepageRoute: typeof CustomizeNotepageRoute
  TopicsTagRoute: typeof TopicsTagRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$notepage': {
      id: '/$notepage'
      path: '/$notepage'
      fullPath: '/$notepage'
      preLoaderRoute: typeof NotepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ink-program': {
      id: '/ink-program'
      path: '/ink-program'
      fullPath: '/ink-program'
      preLoaderRoute: typeof InkProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notella': {
      id: '/notella'
      path: '/notella'
      fullPath: '/notella'
      preLoaderRoute: typeof NotellaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notepages': {
      id: '/notepages'
      path: '/notepages'
      fullPath: '/notepages'
      preLoaderRoute: typeof NotepagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$notepage/': {
      id: '/$notepage/'
      path: '/'
      fullPath: '/$notepage/'
      preLoaderRoute: typeof NotepageIndexRouteImport
      parentRoute: typeof NotepageRoute
    }
    '/$notepage/about': {
      id: '/$notepage/about'
      path: '/about'
      fullPath: '/$notepage/about'
      preLoaderRoute: typeof NotepageAboutRouteImport
      parentRoute: typeof NotepageRoute
    }
    '/$notepage/guestnote': {
      id: '/$notepage/guestnote'
      path: '/guestnote'
      fullPath: '/$notepage/guestnote'
      preLoaderRoute: typeof NotepageGuestnoteRouteImport
      parentRoute: typeof NotepageRoute
    }
    '/$notepage/notes': {
      id: '/$notepage/notes'
      path: '/notes'
      fullPath: '/$notepage/notes'
      preLoaderRoute: typeof NotepageNotesRouteImport
      parentRoute: typeof NotepageRoute
    }
    '/customize/$notepage': {
      id: '/customize/$notepage'
      path: '/customize/$notepage'
      fullPath: '/customize/$notepage'
      preLoaderRoute: typeof CustomizeNotepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notepages/': {
      id: '/notepages/'
      path: '/'
      fullPath: '/notepages/'
      preLoaderRoute: typeof NotepagesIndexRouteImport
      parentRoute: typeof NotepagesRoute
    }
    '/notepages/$notepage': {
      id: '/notepages/$notepage'
      path: '/$notepage'
      fullPath: '/notepages/$notepage'
      preLoaderRoute: typeof NotepagesNotepageRouteImport
      parentRoute: typeof NotepagesRoute
    }
    '/notepages/new': {
      id: '/notepages/new'
      path: '/new'
      fullPath: '/notepages/new'
      preLoaderRoute: typeof NotepagesNewRouteImport
      parentRoute: typeof NotepagesRoute
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$tag': {
      id: '/topics/$tag'
      path: '/topics/$tag'
      fullPath: '/topics/$tag'
      preLoaderRoute: typeof TopicsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$notepage/notepage/$noteId': {
      id: '/$notepage/notepage/$noteId'
      path: '/notepage/$noteId'
      fullPath: '/$notepage/notepage/$noteId'
      preLoaderRoute: typeof NotepageNotepageNoteIdRouteImport
      parentRoute: typeof NotepageRoute
    }
    '/$notepage/notetags/$tag': {
      id: '/$notepage/notetags/$tag'
      path: '/notetags/$tag'
      fullPath: '/$notepage/notetags/$tag'
      preLoaderRoute: typeof NotepageNotetagsTagRouteImport
      parentRoute: typeof NotepageRoute
    }
  }
}

interface NotepageRouteChildren {
  NotepageAboutRoute: typeof NotepageAboutRoute
  NotepageGuestnoteRoute: typeof NotepageGuestnoteRoute
  NotepageNotesRoute: typeof NotepageNotesRoute
  NotepageIndexRoute: typeof NotepageIndexRoute
  NotepageNotepageNoteIdRoute: typeof NotepageNotepageNoteIdRoute
  NotepageNotetagsTagRoute: typeof NotepageNotetagsTagRoute
}

const NotepageRouteChildren: NotepageRouteChildren = {
  NotepageAboutRoute: NotepageAboutRoute,
  NotepageGuestnoteRoute: NotepageGuestnoteRoute,
  NotepageNotesRoute: NotepageNotesRoute,
  NotepageIndexRoute: NotepageIndexRoute,
  NotepageNotepageNoteIdRoute: NotepageNotepageNoteIdRoute,
  NotepageNotetagsTagRoute: NotepageNotetagsTagRoute,
}

const NotepageRouteWithChildren = NotepageRoute._addFileChildren(
  NotepageRouteChildren,
)

interface NotepagesRouteChildren {
  NotepagesNotepageRoute: typeof NotepagesNotepageRoute
  NotepagesNewRoute: typeof NotepagesNewRoute
  NotepagesIndexRoute: typeof NotepagesIndexRoute
}

const NotepagesRouteChildren: NotepagesRouteChildren = {
  NotepagesNotepageRoute: NotepagesNotepageRoute,
  NotepagesNewRoute: NotepagesNewRoute,
  NotepagesIndexRoute: NotepagesIndexRoute,
}

const NotepagesRouteWithChildren = NotepagesRoute._addFileChildren(
  NotepagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotepageRoute: NotepageRouteWithChildren,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  GuidelinesRoute: GuidelinesRoute,
  InkProgramRoute: InkProgramRoute,
  NotellaRoute: NotellaRoute,
  NotepagesRoute: NotepagesRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  WriteRoute: WriteRoute,
  CustomizeNotepageRoute: CustomizeNotepageRoute,
  TopicsTagRoute: TopicsTagRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
